"""
File where all the details of languages supported by the
google translation service are specified.
"""

class Language(object):
    """
    This class represents a language
    """

    languages = {
        'AFRIKAANS' : u"af",
        'ALBANIAN' : u"sq",
        'AMHARIC' : u"am",
        'ARABIC' : u"ar",
        'ARMENIAN' : u"hy",
        'AZERBAIJANI' : u"az",
        'BASQUE' : u"eu",
        'BELARUSIAN' : u"be",
        'BENGALI' : u"bn",
        'BIHARI' : u"bh",
        'BULGARIAN' : u"bg",
        'BURMESE' : u"my",
        'CATALAN' : u"ca",
        'CHEROKEE' : u"chr",
        'CHINESE' : u"zh",
        'CHINESE_SIMPLIFIED' : u"zh-CN",
        'CHINESE_TRADITIONAL' : u"zh-TW",
        'CROATIAN' : u"hr",
        'CZECH' : u"cs",
        'DANISH' : u"da",
        'DHIVEHI' : u"dv",
        'DUTCH' : u"nl",
        'ENGLISH' : u"en",
        'ESPERANTO' : u"eo",
        'ESTONIAN' : u"et",
        'FILIPINO' : u"tl",
        'FINNISH' : u"fi",
        'FRENCH' : u"fr",
        'GALICIAN' : u"gl",
        'GEORGIAN' : u"ka",
        'GERMAN' : u"de",
        'GREEK' : u"el",
        'GUARANI' : u"gn",
        'GUJARATI' : u"gu",
        'HEBREW' : u"iw",
        'HINDI' : u"hi",
        'HUNGARIAN' : u"hu",
        'ICELANDIC' : u"is",
        'INDONESIAN' : u"id",
        'INUKTITUT' : u"iu",
        'ITALIAN' : u"it",
        'JAPANESE' : u"ja",
        'KANNADA' : u"kn",
        'KAZAKH' : u"kk",
        'KHMER' : u"km",
        'KOREAN' : u"ko",
        'KURDISH': u"ku",
        'KYRGYZ': u"ky",
        'LAOTHIAN': u"lo",
        'LATVIAN' : u"lv",
        'LITHUANIAN' : u"lt",
        'MACEDONIAN' : u"mk",
        'MALAY' : u"ms",
        'MALAYALAM' : u"ml",
        'MALTESE' : u"mt",
        'MARATHI' : u"mr",
        'MONGOLIAN' : u"mn",
        'NEPALI' : u"ne",
        'NORWEGIAN' : u"no",
        'ORIYA' : u"or",
        'PASHTO' : u"ps",
        'PERSIAN' : u"fa",
        'POLISH' : u"pl",
        'PORTUGUESE' : u"pt",
        'PUNJABI' : u"pa",
        'ROMANIAN' : u"ro",
        'RUSSIAN' : u"ru",
        'SANSKRIT' : u"sa",
        'SERBIAN' : u"sr",
        'SINDHI' : u"sd",
        'SINHALESE' : u"si",
        'SLOVAK' : u"sk",
        'SLOVENIAN' : u"sl",
        'SPANISH' : u"es",
        'SWAHILI' : u"sw",
        'SWEDISH' : u"sv",
        'TAJIK' : u"tg",
        'TAMIL' : u"ta",
        'TAGALOG' : u"tl",
        'TELUGU' : u"te",
        'THAI' : u"th",
        'TIBETAN' : u"bo",
        'TURKISH' : u"tr",
        'UKRAINIAN' : u"uk",
        'URDU' : u"ur",
        'UZBEK' : u"uz",
        'UIGHUR' : u"ug",
        'VIETNAMESE' : u"vi",
    }

    languages_rev = dict((v,k) for k,v in languages.iteritems())

    languages_choose = ('ARABIC', 'BULGARIAN', 'CHINESE', 'CHINESE_SIMPLIFIED',
                        'CHINESE_TRADITIONAL', 'CATALAN', 'CROATIAN', 'CZECH',
                        'DANISH', 'DUTCH', 'ENGLISH', 'FILIPINO', 'FINNISH',
                        'FRENCH', 'GERMAN', 'GREEK', 'HEBREW', 'HINDI', 'INDONESIAN',
                        'ITALIAN', 'JAPANESE', 'KOREAN', 'LATVIAN', 'LITHUANIAN',
                        'NORWEGIAN', 'POLISH', 'PORTUGUESE', 'ROMANIAN', 'RUSSIAN',
                        'SPANISH', 'SERBIAN', 'SLOVAK', 'SLOVENIAN', 'SWEDISH',
                        'UKRAINIAN', 'VIETNAMESE')

    def __init__(self, language):
        """
        Constructor.

        language -- The language string in all uppercase
        """
        if language.lower() in self.languages_rev:
            self._language = language.lower()
        elif language.upper() in self.languages:
            self._language =  self.languages[language.upper()]
        else:
            raise ValueError("No such language: %s" % language)

    def __str__(self):
        return self._language

    def __cmp__(self, other):
        return cmp(self._language, other._language)

    @staticmethod
    def list_all_languages(separator="\n"):
        """ Returns a string with all available languages (one per line) """
        return str(separator).join(k for k in Language.languages.keys())

class Translation(object):
    """
    This class represents a translation between two languages
    """
    translation_pairs = (

            # ARABIC PAIR
            (Language('ARABIC'), Language('ARABIC')),
            (Language('ARABIC'), Language('BULGARIAN')),
            (Language('ARABIC'), Language('CHINESE')),
            (Language('ARABIC'), Language('CHINESE_TRADITIONAL')),
            (Language('ARABIC'), Language('CHINESE_SIMPLIFIED')),
            (Language('ARABIC'), Language('CATALAN')),
            (Language('ARABIC'), Language('CROATIAN')),
            (Language('ARABIC'), Language('CZECH')),
            (Language('ARABIC'), Language('DANISH')),
            (Language('ARABIC'), Language('DUTCH')),
            (Language('ARABIC'), Language('ENGLISH')),
            (Language('ARABIC'), Language('FILIPINO')),
            (Language('ARABIC'), Language('FINNISH')),
            (Language('ARABIC'), Language('FRENCH')),
            (Language('ARABIC'), Language('GERMAN')),
            (Language('ARABIC'), Language('GREEK')),
            (Language('ARABIC'), Language('HEBREW')),
            (Language('ARABIC'), Language('HINDI')),
            (Language('ARABIC'), Language('INDONESIAN')),
            (Language('ARABIC'), Language('ITALIAN')),
            (Language('ARABIC'), Language('JAPANESE')),
            (Language('ARABIC'), Language('KOREAN')),
            (Language('ARABIC'), Language('LATVIAN')),
            (Language('ARABIC'), Language('LITHUANIAN')),
            (Language('ARABIC'), Language('NORWEGIAN')),
            (Language('ARABIC'), Language('POLISH')),
            (Language('ARABIC'), Language('PORTUGUESE')),
            (Language('ARABIC'), Language('ROMANIAN')),
            (Language('ARABIC'), Language('RUSSIAN')),
            (Language('ARABIC'), Language('SPANISH')),
            (Language('ARABIC'), Language('SERBIAN')),
            (Language('ARABIC'), Language('SLOVAK')),
            (Language('ARABIC'), Language('SLOVENIAN')),
            (Language('ARABIC'), Language('SWEDISH')),
            (Language('ARABIC'), Language('UKRAINIAN')),
            (Language('ARABIC'), Language('VIETNAMESE')),

            # BULGARIAN PAIR
            (Language('BULGARIAN'), Language('ARABIC')),
            (Language('BULGARIAN'), Language('BULGARIAN')),
            (Language('BULGARIAN'), Language('CHINESE')),
            (Language('BULGARIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('BULGARIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('BULGARIAN'), Language('CATALAN')),
            (Language('BULGARIAN'), Language('CROATIAN')),
            (Language('BULGARIAN'), Language('CZECH')),
            (Language('BULGARIAN'), Language('DANISH')),
            (Language('BULGARIAN'), Language('DUTCH')),
            (Language('BULGARIAN'), Language('ENGLISH')),
            (Language('BULGARIAN'), Language('FILIPINO')),
            (Language('BULGARIAN'), Language('FINNISH')),
            (Language('BULGARIAN'), Language('FRENCH')),
            (Language('BULGARIAN'), Language('GERMAN')),
            (Language('BULGARIAN'), Language('GREEK')),
            (Language('BULGARIAN'), Language('HEBREW')),
            (Language('BULGARIAN'), Language('HINDI')),
            (Language('BULGARIAN'), Language('INDONESIAN')),
            (Language('BULGARIAN'), Language('ITALIAN')),
            (Language('BULGARIAN'), Language('JAPANESE')),
            (Language('BULGARIAN'), Language('KOREAN')),
            (Language('BULGARIAN'), Language('LATVIAN')),
            (Language('BULGARIAN'), Language('LITHUANIAN')),
            (Language('BULGARIAN'), Language('NORWEGIAN')),
            (Language('BULGARIAN'), Language('POLISH')),
            (Language('BULGARIAN'), Language('PORTUGUESE')),
            (Language('BULGARIAN'), Language('ROMANIAN')),
            (Language('BULGARIAN'), Language('RUSSIAN')),
            (Language('BULGARIAN'), Language('SPANISH')),
            (Language('BULGARIAN'), Language('SERBIAN')),
            (Language('BULGARIAN'), Language('SLOVAK')),
            (Language('BULGARIAN'), Language('SLOVENIAN')),
            (Language('BULGARIAN'), Language('SWEDISH')),
            (Language('BULGARIAN'), Language('UKRAINIAN')),
            (Language('BULGARIAN'), Language('VIETNAMESE')),


            # CHINESE PAIR
            (Language('CHINESE'), Language('ARABIC')),
            (Language('CHINESE'), Language('BULGARIAN')),
            (Language('CHINESE'), Language('CHINESE')),
            (Language('CHINESE'), Language('CHINESE_TRADITIONAL')),
            (Language('CHINESE'), Language('CHINESE_SIMPLIFIED')),
            (Language('CHINESE'), Language('CATALAN')),
            (Language('CHINESE'), Language('CROATIAN')),
            (Language('CHINESE'), Language('CZECH')),
            (Language('CHINESE'), Language('DANISH')),
            (Language('CHINESE'), Language('DUTCH')),
            (Language('CHINESE'), Language('ENGLISH')),
            (Language('CHINESE'), Language('FILIPINO')),
            (Language('CHINESE'), Language('FINNISH')),
            (Language('CHINESE'), Language('FRENCH')),
            (Language('CHINESE'), Language('GERMAN')),
            (Language('CHINESE'), Language('GREEK')),
            (Language('CHINESE'), Language('HEBREW')),
            (Language('CHINESE'), Language('HINDI')),
            (Language('CHINESE'), Language('INDONESIAN')),
            (Language('CHINESE'), Language('ITALIAN')),
            (Language('CHINESE'), Language('JAPANESE')),
            (Language('CHINESE'), Language('KOREAN')),
            (Language('CHINESE'), Language('LATVIAN')),
            (Language('CHINESE'), Language('LITHUANIAN')),
            (Language('CHINESE'), Language('NORWEGIAN')),
            (Language('CHINESE'), Language('POLISH')),
            (Language('CHINESE'), Language('PORTUGUESE')),
            (Language('CHINESE'), Language('ROMANIAN')),
            (Language('CHINESE'), Language('RUSSIAN')),
            (Language('CHINESE'), Language('SPANISH')),
            (Language('CHINESE'), Language('SERBIAN')),
            (Language('CHINESE'), Language('SLOVAK')),
            (Language('CHINESE'), Language('SLOVENIAN')),
            (Language('CHINESE'), Language('SWEDISH')),
            (Language('CHINESE'), Language('UKRAINIAN')),
            (Language('CHINESE'), Language('VIETNAMESE')),

            # CHINESE_TRADITIONAL PAIR
            (Language('CHINESE_TRADITIONAL'), Language('ARABIC')),
            (Language('CHINESE_TRADITIONAL'), Language('BULGARIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('CHINESE')),
            (Language('CHINESE_TRADITIONAL'), Language('CHINESE_TRADITIONAL')),
            (Language('CHINESE_TRADITIONAL'), Language('CHINESE_SIMPLIFIED')),
            (Language('CHINESE_TRADITIONAL'), Language('CATALAN')),
            (Language('CHINESE_TRADITIONAL'), Language('CROATIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('CZECH')),
            (Language('CHINESE_TRADITIONAL'), Language('DANISH')),
            (Language('CHINESE_TRADITIONAL'), Language('DUTCH')),
            (Language('CHINESE_TRADITIONAL'), Language('ENGLISH')),
            (Language('CHINESE_TRADITIONAL'), Language('FILIPINO')),
            (Language('CHINESE_TRADITIONAL'), Language('FINNISH')),
            (Language('CHINESE_TRADITIONAL'), Language('FRENCH')),
            (Language('CHINESE_TRADITIONAL'), Language('GERMAN')),
            (Language('CHINESE_TRADITIONAL'), Language('GREEK')),
            (Language('CHINESE_TRADITIONAL'), Language('HEBREW')),
            (Language('CHINESE_TRADITIONAL'), Language('HINDI')),
            (Language('CHINESE_TRADITIONAL'), Language('INDONESIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('ITALIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('JAPANESE')),
            (Language('CHINESE_TRADITIONAL'), Language('KOREAN')),
            (Language('CHINESE_TRADITIONAL'), Language('LATVIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('LITHUANIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('NORWEGIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('POLISH')),
            (Language('CHINESE_TRADITIONAL'), Language('PORTUGUESE')),
            (Language('CHINESE_TRADITIONAL'), Language('ROMANIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('RUSSIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('SPANISH')),
            (Language('CHINESE_TRADITIONAL'), Language('SERBIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('SLOVAK')),
            (Language('CHINESE_TRADITIONAL'), Language('SLOVENIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('SWEDISH')),
            (Language('CHINESE_TRADITIONAL'), Language('UKRAINIAN')),
            (Language('CHINESE_TRADITIONAL'), Language('VIETNAMESE')),

            #CHINESE_SIMPLIFIED PAIR
            (Language('CHINESE_SIMPLIFIED'), Language('ARABIC')),
            (Language('CHINESE_SIMPLIFIED'), Language('BULGARIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('CHINESE')),
            (Language('CHINESE_SIMPLIFIED'), Language('CHINESE_TRADITIONAL')),
            (Language('CHINESE_SIMPLIFIED'), Language('CHINESE_SIMPLIFIED')),
            (Language('CHINESE_SIMPLIFIED'), Language('CATALAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('CROATIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('CZECH')),
            (Language('CHINESE_SIMPLIFIED'), Language('DANISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('DUTCH')),
            (Language('CHINESE_SIMPLIFIED'), Language('ENGLISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('FILIPINO')),
            (Language('CHINESE_SIMPLIFIED'), Language('FINNISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('FRENCH')),
            (Language('CHINESE_SIMPLIFIED'), Language('GERMAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('GREEK')),
            (Language('CHINESE_SIMPLIFIED'), Language('HEBREW')),
            (Language('CHINESE_SIMPLIFIED'), Language('HINDI')),
            (Language('CHINESE_SIMPLIFIED'), Language('INDONESIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('ITALIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('JAPANESE')),
            (Language('CHINESE_SIMPLIFIED'), Language('KOREAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('LATVIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('LITHUANIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('NORWEGIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('POLISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('PORTUGUESE')),
            (Language('CHINESE_SIMPLIFIED'), Language('ROMANIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('RUSSIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('SPANISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('SERBIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('SLOVAK')),
            (Language('CHINESE_SIMPLIFIED'), Language('SLOVENIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('SWEDISH')),
            (Language('CHINESE_SIMPLIFIED'), Language('UKRAINIAN')),
            (Language('CHINESE_SIMPLIFIED'), Language('VIETNAMESE')),

            # CATALAN PAIR
            (Language('CATALAN'), Language('ARABIC')),
            (Language('CATALAN'), Language('BULGARIAN')),
            (Language('CATALAN'), Language('CHINESE')),
            (Language('CATALAN'), Language('CHINESE_TRADITIONAL')),
            (Language('CATALAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('CATALAN'), Language('CATALAN')),
            (Language('CATALAN'), Language('CROATIAN')),
            (Language('CATALAN'), Language('CZECH')),
            (Language('CATALAN'), Language('DANISH')),
            (Language('CATALAN'), Language('DUTCH')),
            (Language('CATALAN'), Language('ENGLISH')),
            (Language('CATALAN'), Language('FILIPINO')),
            (Language('CATALAN'), Language('FINNISH')),
            (Language('CATALAN'), Language('FRENCH')),
            (Language('CATALAN'), Language('GERMAN')),
            (Language('CATALAN'), Language('GREEK')),
            (Language('CATALAN'), Language('HEBREW')),
            (Language('CATALAN'), Language('HINDI')),
            (Language('CATALAN'), Language('INDONESIAN')),
            (Language('CATALAN'), Language('ITALIAN')),
            (Language('CATALAN'), Language('JAPANESE')),
            (Language('CATALAN'), Language('KOREAN')),
            (Language('CATALAN'), Language('LATVIAN')),
            (Language('CATALAN'), Language('LITHUANIAN')),
            (Language('CATALAN'), Language('NORWEGIAN')),
            (Language('CATALAN'), Language('POLISH')),
            (Language('CATALAN'), Language('PORTUGUESE')),
            (Language('CATALAN'), Language('ROMANIAN')),
            (Language('CATALAN'), Language('RUSSIAN')),
            (Language('CATALAN'), Language('SPANISH')),
            (Language('CATALAN'), Language('SERBIAN')),
            (Language('CATALAN'), Language('SLOVAK')),
            (Language('CATALAN'), Language('SLOVENIAN')),
            (Language('CATALAN'), Language('SWEDISH')),
            (Language('CATALAN'), Language('UKRAINIAN')),
            (Language('CATALAN'), Language('VIETNAMESE')),

            # CROATIAN PAIR
            (Language('CROATIAN'), Language('ARABIC')),
            (Language('CROATIAN'), Language('BULGARIAN')),
            (Language('CROATIAN'), Language('CHINESE')),
            (Language('CROATIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('CROATIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('CROATIAN'), Language('CATALAN')),
            (Language('CROATIAN'), Language('CROATIAN')),
            (Language('CROATIAN'), Language('CZECH')),
            (Language('CROATIAN'), Language('DANISH')),
            (Language('CROATIAN'), Language('DUTCH')),
            (Language('CROATIAN'), Language('ENGLISH')),
            (Language('CROATIAN'), Language('FILIPINO')),
            (Language('CROATIAN'), Language('FINNISH')),
            (Language('CROATIAN'), Language('FRENCH')),
            (Language('CROATIAN'), Language('GERMAN')),
            (Language('CROATIAN'), Language('GREEK')),
            (Language('CROATIAN'), Language('HEBREW')),
            (Language('CROATIAN'), Language('HINDI')),
            (Language('CROATIAN'), Language('INDONESIAN')),
            (Language('CROATIAN'), Language('ITALIAN')),
            (Language('CROATIAN'), Language('JAPANESE')),
            (Language('CROATIAN'), Language('KOREAN')),
            (Language('CROATIAN'), Language('LATVIAN')),
            (Language('CROATIAN'), Language('LITHUANIAN')),
            (Language('CROATIAN'), Language('NORWEGIAN')),
            (Language('CROATIAN'), Language('POLISH')),
            (Language('CROATIAN'), Language('PORTUGUESE')),
            (Language('CROATIAN'), Language('ROMANIAN')),
            (Language('CROATIAN'), Language('RUSSIAN')),
            (Language('CROATIAN'), Language('SPANISH')),
            (Language('CROATIAN'), Language('SERBIAN')),
            (Language('CROATIAN'), Language('SLOVAK')),
            (Language('CROATIAN'), Language('SLOVENIAN')),
            (Language('CROATIAN'), Language('SWEDISH')),
            (Language('CROATIAN'), Language('UKRAINIAN')),
            (Language('CROATIAN'), Language('VIETNAMESE')),

            # DANISH PAIR
            (Language('DANISH'), Language('ARABIC')),
            (Language('DANISH'), Language('BULGARIAN')),
            (Language('DANISH'), Language('CHINESE')),
            (Language('DANISH'), Language('CHINESE_TRADITIONAL')),
            (Language('DANISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('DANISH'), Language('CATALAN')),
            (Language('DANISH'), Language('CROATIAN')),
            (Language('DANISH'), Language('CZECH')),
            (Language('DANISH'), Language('DANISH')),
            (Language('DANISH'), Language('DUTCH')),
            (Language('DANISH'), Language('ENGLISH')),
            (Language('DANISH'), Language('FILIPINO')),
            (Language('DANISH'), Language('FINNISH')),
            (Language('DANISH'), Language('FRENCH')),
            (Language('DANISH'), Language('GERMAN')),
            (Language('DANISH'), Language('GREEK')),
            (Language('DANISH'), Language('HEBREW')),
            (Language('DANISH'), Language('HINDI')),
            (Language('DANISH'), Language('INDONESIAN')),
            (Language('DANISH'), Language('ITALIAN')),
            (Language('DANISH'), Language('JAPANESE')),
            (Language('DANISH'), Language('KOREAN')),
            (Language('DANISH'), Language('LATVIAN')),
            (Language('DANISH'), Language('LITHUANIAN')),
            (Language('DANISH'), Language('NORWEGIAN')),
            (Language('DANISH'), Language('POLISH')),
            (Language('DANISH'), Language('PORTUGUESE')),
            (Language('DANISH'), Language('ROMANIAN')),
            (Language('DANISH'), Language('RUSSIAN')),
            (Language('DANISH'), Language('SPANISH')),
            (Language('DANISH'), Language('SERBIAN')),
            (Language('DANISH'), Language('SLOVAK')),
            (Language('DANISH'), Language('SLOVENIAN')),
            (Language('DANISH'), Language('SWEDISH')),
            (Language('DANISH'), Language('UKRAINIAN')),
            (Language('DANISH'), Language('VIETNAMESE')),

            # DUTCH PAIR
             (Language('DUTCH'), Language('ARABIC')),
            (Language('DUTCH'), Language('BULGARIAN')),
            (Language('DUTCH'), Language('CHINESE')),
            (Language('DUTCH'), Language('CHINESE_TRADITIONAL')),
            (Language('DUTCH'), Language('CHINESE_SIMPLIFIED')),
            (Language('DUTCH'), Language('CATALAN')),
            (Language('DUTCH'), Language('CROATIAN')),
            (Language('DUTCH'), Language('CZECH')),
            (Language('DUTCH'), Language('DANISH')),
            (Language('DUTCH'), Language('DUTCH')),
            (Language('DUTCH'), Language('ENGLISH')),
            (Language('DUTCH'), Language('FILIPINO')),
            (Language('DUTCH'), Language('FINNISH')),
            (Language('DUTCH'), Language('FRENCH')),
            (Language('DUTCH'), Language('GERMAN')),
            (Language('DUTCH'), Language('GREEK')),
            (Language('DUTCH'), Language('HEBREW')),
            (Language('DUTCH'), Language('HINDI')),
            (Language('DUTCH'), Language('INDONESIAN')),
            (Language('DUTCH'), Language('ITALIAN')),
            (Language('DUTCH'), Language('JAPANESE')),
            (Language('DUTCH'), Language('KOREAN')),
            (Language('DUTCH'), Language('LATVIAN')),
            (Language('DUTCH'), Language('LITHUANIAN')),
            (Language('DUTCH'), Language('NORWEGIAN')),
            (Language('DUTCH'), Language('POLISH')),
            (Language('DUTCH'), Language('PORTUGUESE')),
            (Language('DUTCH'), Language('ROMANIAN')),
            (Language('DUTCH'), Language('RUSSIAN')),
            (Language('DUTCH'), Language('SPANISH')),
            (Language('DUTCH'), Language('SERBIAN')),
            (Language('DUTCH'), Language('SLOVAK')),
            (Language('DUTCH'), Language('SLOVENIAN')),
            (Language('DUTCH'), Language('SWEDISH')),
            (Language('DUTCH'), Language('UKRAINIAN')),
            (Language('DUTCH'), Language('VIETNAMESE')),

            # ENGLISH PAIR
            (Language('ENGLISH'), Language('ARABIC')),
            (Language('ENGLISH'), Language('BULGARIAN')),
            (Language('ENGLISH'), Language('CHINESE')),
            (Language('ENGLISH'), Language('CHINESE_TRADITIONAL')),
            (Language('ENGLISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('ENGLISH'), Language('CATALAN')),
            (Language('ENGLISH'), Language('CROATIAN')),
            (Language('ENGLISH'), Language('CZECH')),
            (Language('ENGLISH'), Language('DANISH')),
            (Language('ENGLISH'), Language('DUTCH')),
            (Language('ENGLISH'), Language('ENGLISH')),
            (Language('ENGLISH'), Language('FILIPINO')),
            (Language('ENGLISH'), Language('FINNISH')),
            (Language('ENGLISH'), Language('FRENCH')),
            (Language('ENGLISH'), Language('GERMAN')),
            (Language('ENGLISH'), Language('GREEK')),
            (Language('ENGLISH'), Language('HEBREW')),
            (Language('ENGLISH'), Language('HINDI')),
            (Language('ENGLISH'), Language('INDONESIAN')),
            (Language('ENGLISH'), Language('ITALIAN')),
            (Language('ENGLISH'), Language('JAPANESE')),
            (Language('ENGLISH'), Language('KOREAN')),
            (Language('ENGLISH'), Language('LATVIAN')),
            (Language('ENGLISH'), Language('LITHUANIAN')),
            (Language('ENGLISH'), Language('NORWEGIAN')),
            (Language('ENGLISH'), Language('POLISH')),
            (Language('ENGLISH'), Language('PORTUGUESE')),
            (Language('ENGLISH'), Language('ROMANIAN')),
            (Language('ENGLISH'), Language('RUSSIAN')),
            (Language('ENGLISH'), Language('SPANISH')),
            (Language('ENGLISH'), Language('SERBIAN')),
            (Language('ENGLISH'), Language('SLOVAK')),
            (Language('ENGLISH'), Language('SLOVENIAN')),
            (Language('ENGLISH'), Language('SWEDISH')),
            (Language('ENGLISH'), Language('UKRAINIAN')),
            (Language('ENGLISH'), Language('VIETNAMESE')),

            # FILIPINO PAIR
            (Language('FILIPINO'), Language('ARABIC')),
            (Language('FILIPINO'), Language('BULGARIAN')),
            (Language('FILIPINO'), Language('CHINESE')),
            (Language('FILIPINO'), Language('CHINESE_TRADITIONAL')),
            (Language('FILIPINO'), Language('CHINESE_SIMPLIFIED')),
            (Language('FILIPINO'), Language('CATALAN')),
            (Language('FILIPINO'), Language('CROATIAN')),
            (Language('FILIPINO'), Language('CZECH')),
            (Language('FILIPINO'), Language('DANISH')),
            (Language('FILIPINO'), Language('DUTCH')),
            (Language('FILIPINO'), Language('ENGLISH')),
            (Language('FILIPINO'), Language('FILIPINO')),
            (Language('FILIPINO'), Language('FINNISH')),
            (Language('FILIPINO'), Language('FRENCH')),
            (Language('FILIPINO'), Language('GERMAN')),
            (Language('FILIPINO'), Language('GREEK')),
            (Language('FILIPINO'), Language('HEBREW')),
            (Language('FILIPINO'), Language('HINDI')),
            (Language('FILIPINO'), Language('INDONESIAN')),
            (Language('FILIPINO'), Language('ITALIAN')),
            (Language('FILIPINO'), Language('JAPANESE')),
            (Language('FILIPINO'), Language('KOREAN')),
            (Language('FILIPINO'), Language('LATVIAN')),
            (Language('FILIPINO'), Language('LITHUANIAN')),
            (Language('FILIPINO'), Language('NORWEGIAN')),
            (Language('FILIPINO'), Language('POLISH')),
            (Language('FILIPINO'), Language('PORTUGUESE')),
            (Language('FILIPINO'), Language('ROMANIAN')),
            (Language('FILIPINO'), Language('RUSSIAN')),
            (Language('FILIPINO'), Language('SPANISH')),
            (Language('FILIPINO'), Language('SERBIAN')),
            (Language('FILIPINO'), Language('SLOVAK')),
            (Language('FILIPINO'), Language('SLOVENIAN')),
            (Language('FILIPINO'), Language('SWEDISH')),
            (Language('FILIPINO'), Language('UKRAINIAN')),
            (Language('FILIPINO'), Language('VIETNAMESE')),

            # FINNISH PAIR
            (Language('FINNISH'), Language('ARABIC')),
            (Language('FINNISH'), Language('BULGARIAN')),
            (Language('FINNISH'), Language('CHINESE')),
            (Language('FINNISH'), Language('CHINESE_TRADITIONAL')),
            (Language('FINNISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('FINNISH'), Language('CATALAN')),
            (Language('FINNISH'), Language('CROATIAN')),
            (Language('FINNISH'), Language('CZECH')),
            (Language('FINNISH'), Language('DANISH')),
            (Language('FINNISH'), Language('DUTCH')),
            (Language('FINNISH'), Language('ENGLISH')),
            (Language('FINNISH'), Language('FILIPINO')),
            (Language('FINNISH'), Language('FINNISH')),
            (Language('FINNISH'), Language('FRENCH')),
            (Language('FINNISH'), Language('GERMAN')),
            (Language('FINNISH'), Language('GREEK')),
            (Language('FINNISH'), Language('HEBREW')),
            (Language('FINNISH'), Language('HINDI')),
            (Language('FINNISH'), Language('INDONESIAN')),
            (Language('FINNISH'), Language('ITALIAN')),
            (Language('FINNISH'), Language('JAPANESE')),
            (Language('FINNISH'), Language('KOREAN')),
            (Language('FINNISH'), Language('LATVIAN')),
            (Language('FINNISH'), Language('LITHUANIAN')),
            (Language('FINNISH'), Language('NORWEGIAN')),
            (Language('FINNISH'), Language('POLISH')),
            (Language('FINNISH'), Language('PORTUGUESE')),
            (Language('FINNISH'), Language('ROMANIAN')),
            (Language('FINNISH'), Language('RUSSIAN')),
            (Language('FINNISH'), Language('SPANISH')),
            (Language('FINNISH'), Language('SERBIAN')),
            (Language('FINNISH'), Language('SLOVAK')),
            (Language('FINNISH'), Language('SLOVENIAN')),
            (Language('FINNISH'), Language('SWEDISH')),
            (Language('FINNISH'), Language('UKRAINIAN')),
            (Language('FINNISH'), Language('VIETNAMESE')),

            # FRENCH PAIR
            (Language('FRENCH'), Language('ARABIC')),
            (Language('FRENCH'), Language('BULGARIAN')),
            (Language('FRENCH'), Language('CHINESE')),
            (Language('FRENCH'), Language('CHINESE_TRADITIONAL')),
            (Language('FRENCH'), Language('CHINESE_SIMPLIFIED')),
            (Language('FRENCH'), Language('CATALAN')),
            (Language('FRENCH'), Language('CROATIAN')),
            (Language('FRENCH'), Language('CZECH')),
            (Language('FRENCH'), Language('DANISH')),
            (Language('FRENCH'), Language('DUTCH')),
            (Language('FRENCH'), Language('ENGLISH')),
            (Language('FRENCH'), Language('FILIPINO')),
            (Language('FRENCH'), Language('FINNISH')),
            (Language('FRENCH'), Language('FRENCH')),
            (Language('FRENCH'), Language('GERMAN')),
            (Language('FRENCH'), Language('GREEK')),
            (Language('FRENCH'), Language('HEBREW')),
            (Language('FRENCH'), Language('HINDI')),
            (Language('FRENCH'), Language('INDONESIAN')),
            (Language('FRENCH'), Language('ITALIAN')),
            (Language('FRENCH'), Language('JAPANESE')),
            (Language('FRENCH'), Language('KOREAN')),
            (Language('FRENCH'), Language('LATVIAN')),
            (Language('FRENCH'), Language('LITHUANIAN')),
            (Language('FRENCH'), Language('NORWEGIAN')),
            (Language('FRENCH'), Language('POLISH')),
            (Language('FRENCH'), Language('PORTUGUESE')),
            (Language('FRENCH'), Language('ROMANIAN')),
            (Language('FRENCH'), Language('RUSSIAN')),
            (Language('FRENCH'), Language('SPANISH')),
            (Language('FRENCH'), Language('SERBIAN')),
            (Language('FRENCH'), Language('SLOVAK')),
            (Language('FRENCH'), Language('SLOVENIAN')),
            (Language('FRENCH'), Language('SWEDISH')),
            (Language('FRENCH'), Language('UKRAINIAN')),
            (Language('FRENCH'), Language('VIETNAMESE')),

            # GERMAN PAIR
            (Language('GERMAN'), Language('ARABIC')),
            (Language('GERMAN'), Language('BULGARIAN')),
            (Language('GERMAN'), Language('CHINESE')),
            (Language('GERMAN'), Language('CHINESE_TRADITIONAL')),
            (Language('GERMAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('GERMAN'), Language('CATALAN')),
            (Language('GERMAN'), Language('CROATIAN')),
            (Language('GERMAN'), Language('CZECH')),
            (Language('GERMAN'), Language('DANISH')),
            (Language('GERMAN'), Language('DUTCH')),
            (Language('GERMAN'), Language('ENGLISH')),
            (Language('GERMAN'), Language('FILIPINO')),
            (Language('GERMAN'), Language('FINNISH')),
            (Language('GERMAN'), Language('FRENCH')),
            (Language('GERMAN'), Language('GERMAN')),
            (Language('GERMAN'), Language('GREEK')),
            (Language('GERMAN'), Language('HEBREW')),
            (Language('GERMAN'), Language('HINDI')),
            (Language('GERMAN'), Language('INDONESIAN')),
            (Language('GERMAN'), Language('ITALIAN')),
            (Language('GERMAN'), Language('JAPANESE')),
            (Language('GERMAN'), Language('KOREAN')),
            (Language('GERMAN'), Language('LATVIAN')),
            (Language('GERMAN'), Language('LITHUANIAN')),
            (Language('GERMAN'), Language('NORWEGIAN')),
            (Language('GERMAN'), Language('POLISH')),
            (Language('GERMAN'), Language('PORTUGUESE')),
            (Language('GERMAN'), Language('ROMANIAN')),
            (Language('GERMAN'), Language('RUSSIAN')),
            (Language('GERMAN'), Language('SPANISH')),
            (Language('GERMAN'), Language('SERBIAN')),
            (Language('GERMAN'), Language('SLOVAK')),
            (Language('GERMAN'), Language('SLOVENIAN')),
            (Language('GERMAN'), Language('SWEDISH')),
            (Language('GERMAN'), Language('UKRAINIAN')),
            (Language('GERMAN'), Language('VIETNAMESE')),

            # GREEK PAIR
            (Language('GREEK'), Language('ARABIC')),
            (Language('GREEK'), Language('BULGARIAN')),
            (Language('GREEK'), Language('CHINESE')),
            (Language('GREEK'), Language('CHINESE_TRADITIONAL')),
            (Language('GREEK'), Language('CHINESE_SIMPLIFIED')),
            (Language('GREEK'), Language('CATALAN')),
            (Language('GREEK'), Language('CROATIAN')),
            (Language('GREEK'), Language('CZECH')),
            (Language('GREEK'), Language('DANISH')),
            (Language('GREEK'), Language('DUTCH')),
            (Language('GREEK'), Language('ENGLISH')),
            (Language('GREEK'), Language('FILIPINO')),
            (Language('GREEK'), Language('FINNISH')),
            (Language('GREEK'), Language('FRENCH')),
            (Language('GREEK'), Language('GERMAN')),
            (Language('GREEK'), Language('GREEK')),
            (Language('GREEK'), Language('HEBREW')),
            (Language('GREEK'), Language('HINDI')),
            (Language('GREEK'), Language('INDONESIAN')),
            (Language('GREEK'), Language('ITALIAN')),
            (Language('GREEK'), Language('JAPANESE')),
            (Language('GREEK'), Language('KOREAN')),
            (Language('GREEK'), Language('LATVIAN')),
            (Language('GREEK'), Language('LITHUANIAN')),
            (Language('GREEK'), Language('NORWEGIAN')),
            (Language('GREEK'), Language('POLISH')),
            (Language('GREEK'), Language('PORTUGUESE')),
            (Language('GREEK'), Language('ROMANIAN')),
            (Language('GREEK'), Language('RUSSIAN')),
            (Language('GREEK'), Language('SPANISH')),
            (Language('GREEK'), Language('SERBIAN')),
            (Language('GREEK'), Language('SLOVAK')),
            (Language('GREEK'), Language('SLOVENIAN')),
            (Language('GREEK'), Language('SWEDISH')),
            (Language('GREEK'), Language('UKRAINIAN')),
            (Language('GREEK'), Language('VIETNAMESE')),

            # HEBREW PAIR
            (Language('HEBREW'), Language('ARABIC')),
            (Language('HEBREW'), Language('BULGARIAN')),
            (Language('HEBREW'), Language('CHINESE')),
            (Language('HEBREW'), Language('CHINESE_TRADITIONAL')),
            (Language('HEBREW'), Language('CHINESE_SIMPLIFIED')),
            (Language('HEBREW'), Language('CATALAN')),
            (Language('HEBREW'), Language('CROATIAN')),
            (Language('HEBREW'), Language('CZECH')),
            (Language('HEBREW'), Language('DANISH')),
            (Language('HEBREW'), Language('DUTCH')),
            (Language('HEBREW'), Language('ENGLISH')),
            (Language('HEBREW'), Language('FILIPINO')),
            (Language('HEBREW'), Language('FINNISH')),
            (Language('HEBREW'), Language('FRENCH')),
            (Language('HEBREW'), Language('GERMAN')),
            (Language('HEBREW'), Language('GREEK')),
            (Language('HEBREW'), Language('HEBREW')),
            (Language('HEBREW'), Language('HINDI')),
            (Language('HEBREW'), Language('INDONESIAN')),
            (Language('HEBREW'), Language('ITALIAN')),
            (Language('HEBREW'), Language('JAPANESE')),
            (Language('HEBREW'), Language('KOREAN')),
            (Language('HEBREW'), Language('LATVIAN')),
            (Language('HEBREW'), Language('LITHUANIAN')),
            (Language('HEBREW'), Language('NORWEGIAN')),
            (Language('HEBREW'), Language('POLISH')),
            (Language('HEBREW'), Language('PORTUGUESE')),
            (Language('HEBREW'), Language('ROMANIAN')),
            (Language('HEBREW'), Language('RUSSIAN')),
            (Language('HEBREW'), Language('SPANISH')),
            (Language('HEBREW'), Language('SERBIAN')),
            (Language('HEBREW'), Language('SLOVAK')),
            (Language('HEBREW'), Language('SLOVENIAN')),
            (Language('HEBREW'), Language('SWEDISH')),
            (Language('HEBREW'), Language('UKRAINIAN')),
            (Language('HEBREW'), Language('VIETNAMESE')),

            # HINDI PAIR
            (Language('HINDI'), Language('ARABIC')),
            (Language('HINDI'), Language('BULGARIAN')),
            (Language('HINDI'), Language('CHINESE')),
            (Language('HINDI'), Language('CHINESE_TRADITIONAL')),
            (Language('HINDI'), Language('CHINESE_SIMPLIFIED')),
            (Language('HINDI'), Language('CATALAN')),
            (Language('HINDI'), Language('CROATIAN')),
            (Language('HINDI'), Language('CZECH')),
            (Language('HINDI'), Language('DANISH')),
            (Language('HINDI'), Language('DUTCH')),
            (Language('HINDI'), Language('ENGLISH')),
            (Language('HINDI'), Language('FILIPINO')),
            (Language('HINDI'), Language('FINNISH')),
            (Language('HINDI'), Language('FRENCH')),
            (Language('HINDI'), Language('GERMAN')),
            (Language('HINDI'), Language('GREEK')),
            (Language('HINDI'), Language('HEBREW')),
            (Language('HINDI'), Language('HINDI')),
            (Language('HINDI'), Language('INDONESIAN')),
            (Language('HINDI'), Language('ITALIAN')),
            (Language('HINDI'), Language('JAPANESE')),
            (Language('HINDI'), Language('KOREAN')),
            (Language('HINDI'), Language('LATVIAN')),
            (Language('HINDI'), Language('LITHUANIAN')),
            (Language('HINDI'), Language('NORWEGIAN')),
            (Language('HINDI'), Language('POLISH')),
            (Language('HINDI'), Language('PORTUGUESE')),
            (Language('HINDI'), Language('ROMANIAN')),
            (Language('HINDI'), Language('RUSSIAN')),
            (Language('HINDI'), Language('SPANISH')),
            (Language('HINDI'), Language('SERBIAN')),
            (Language('HINDI'), Language('SLOVAK')),
            (Language('HINDI'), Language('SLOVENIAN')),
            (Language('HINDI'), Language('SWEDISH')),
            (Language('HINDI'), Language('UKRAINIAN')),
            (Language('HINDI'), Language('VIETNAMESE')),

            # INDONESIAN PAIR
            (Language('INDONESIAN'), Language('ARABIC')),
            (Language('INDONESIAN'), Language('BULGARIAN')),
            (Language('INDONESIAN'), Language('CHINESE')),
            (Language('INDONESIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('INDONESIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('INDONESIAN'), Language('CATALAN')),
            (Language('INDONESIAN'), Language('CROATIAN')),
            (Language('INDONESIAN'), Language('CZECH')),
            (Language('INDONESIAN'), Language('DANISH')),
            (Language('INDONESIAN'), Language('DUTCH')),
            (Language('INDONESIAN'), Language('ENGLISH')),
            (Language('INDONESIAN'), Language('FILIPINO')),
            (Language('INDONESIAN'), Language('FINNISH')),
            (Language('INDONESIAN'), Language('FRENCH')),
            (Language('INDONESIAN'), Language('GERMAN')),
            (Language('INDONESIAN'), Language('GREEK')),
            (Language('INDONESIAN'), Language('HEBREW')),
            (Language('INDONESIAN'), Language('HINDI')),
            (Language('INDONESIAN'), Language('INDONESIAN')),
            (Language('INDONESIAN'), Language('ITALIAN')),
            (Language('INDONESIAN'), Language('JAPANESE')),
            (Language('INDONESIAN'), Language('KOREAN')),
            (Language('INDONESIAN'), Language('LATVIAN')),
            (Language('INDONESIAN'), Language('LITHUANIAN')),
            (Language('INDONESIAN'), Language('NORWEGIAN')),
            (Language('INDONESIAN'), Language('POLISH')),
            (Language('INDONESIAN'), Language('PORTUGUESE')),
            (Language('INDONESIAN'), Language('ROMANIAN')),
            (Language('INDONESIAN'), Language('RUSSIAN')),
            (Language('INDONESIAN'), Language('SPANISH')),
            (Language('INDONESIAN'), Language('SERBIAN')),
            (Language('INDONESIAN'), Language('SLOVAK')),
            (Language('INDONESIAN'), Language('SLOVENIAN')),
            (Language('INDONESIAN'), Language('SWEDISH')),
            (Language('INDONESIAN'), Language('UKRAINIAN')),
            (Language('INDONESIAN'), Language('VIETNAMESE')),

            # ITALIAN PAIR
            (Language('ITALIAN'), Language('ARABIC')),
            (Language('ITALIAN'), Language('BULGARIAN')),
            (Language('ITALIAN'), Language('CHINESE')),
            (Language('ITALIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('ITALIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('ITALIAN'), Language('CATALAN')),
            (Language('ITALIAN'), Language('CROATIAN')),
            (Language('ITALIAN'), Language('CZECH')),
            (Language('ITALIAN'), Language('DANISH')),
            (Language('ITALIAN'), Language('DUTCH')),
            (Language('ITALIAN'), Language('ENGLISH')),
            (Language('ITALIAN'), Language('FILIPINO')),
            (Language('ITALIAN'), Language('FINNISH')),
            (Language('ITALIAN'), Language('FRENCH')),
            (Language('ITALIAN'), Language('GERMAN')),
            (Language('ITALIAN'), Language('GREEK')),
            (Language('ITALIAN'), Language('HEBREW')),
            (Language('ITALIAN'), Language('HINDI')),
            (Language('ITALIAN'), Language('INDONESIAN')),
            (Language('ITALIAN'), Language('ITALIAN')),
            (Language('ITALIAN'), Language('JAPANESE')),
            (Language('ITALIAN'), Language('KOREAN')),
            (Language('ITALIAN'), Language('LATVIAN')),
            (Language('ITALIAN'), Language('LITHUANIAN')),
            (Language('ITALIAN'), Language('NORWEGIAN')),
            (Language('ITALIAN'), Language('POLISH')),
            (Language('ITALIAN'), Language('PORTUGUESE')),
            (Language('ITALIAN'), Language('ROMANIAN')),
            (Language('ITALIAN'), Language('RUSSIAN')),
            (Language('ITALIAN'), Language('SPANISH')),
            (Language('ITALIAN'), Language('SERBIAN')),
            (Language('ITALIAN'), Language('SLOVAK')),
            (Language('ITALIAN'), Language('SLOVENIAN')),
            (Language('ITALIAN'), Language('SWEDISH')),
            (Language('ITALIAN'), Language('UKRAINIAN')),
            (Language('ITALIAN'), Language('VIETNAMESE')),

            # JAPANESE PAIR
            (Language('JAPANESE'), Language('ARABIC')),
            (Language('JAPANESE'), Language('BULGARIAN')),
            (Language('JAPANESE'), Language('CHINESE')),
            (Language('JAPANESE'), Language('CHINESE_TRADITIONAL')),
            (Language('JAPANESE'), Language('CHINESE_SIMPLIFIED')),
            (Language('JAPANESE'), Language('CATALAN')),
            (Language('JAPANESE'), Language('CROATIAN')),
            (Language('JAPANESE'), Language('CZECH')),
            (Language('JAPANESE'), Language('DANISH')),
            (Language('JAPANESE'), Language('DUTCH')),
            (Language('JAPANESE'), Language('ENGLISH')),
            (Language('JAPANESE'), Language('FILIPINO')),
            (Language('JAPANESE'), Language('FINNISH')),
            (Language('JAPANESE'), Language('FRENCH')),
            (Language('JAPANESE'), Language('GERMAN')),
            (Language('JAPANESE'), Language('GREEK')),
            (Language('JAPANESE'), Language('HEBREW')),
            (Language('JAPANESE'), Language('HINDI')),
            (Language('JAPANESE'), Language('INDONESIAN')),
            (Language('JAPANESE'), Language('ITALIAN')),
            (Language('JAPANESE'), Language('JAPANESE')),
            (Language('JAPANESE'), Language('KOREAN')),
            (Language('JAPANESE'), Language('LATVIAN')),
            (Language('JAPANESE'), Language('LITHUANIAN')),
            (Language('JAPANESE'), Language('NORWEGIAN')),
            (Language('JAPANESE'), Language('POLISH')),
            (Language('JAPANESE'), Language('PORTUGUESE')),
            (Language('JAPANESE'), Language('ROMANIAN')),
            (Language('JAPANESE'), Language('RUSSIAN')),
            (Language('JAPANESE'), Language('SPANISH')),
            (Language('JAPANESE'), Language('SERBIAN')),
            (Language('JAPANESE'), Language('SLOVAK')),
            (Language('JAPANESE'), Language('SLOVENIAN')),
            (Language('JAPANESE'), Language('SWEDISH')),
            (Language('JAPANESE'), Language('UKRAINIAN')),
            (Language('JAPANESE'), Language('VIETNAMESE')),

            # KOREAN PAIR
            (Language('KOREAN'), Language('ARABIC')),
            (Language('KOREAN'), Language('BULGARIAN')),
            (Language('KOREAN'), Language('CHINESE')),
            (Language('KOREAN'), Language('CHINESE_TRADITIONAL')),
            (Language('KOREAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('KOREAN'), Language('CATALAN')),
            (Language('KOREAN'), Language('CROATIAN')),
            (Language('KOREAN'), Language('CZECH')),
            (Language('KOREAN'), Language('DANISH')),
            (Language('KOREAN'), Language('DUTCH')),
            (Language('KOREAN'), Language('ENGLISH')),
            (Language('KOREAN'), Language('FILIPINO')),
            (Language('KOREAN'), Language('FINNISH')),
            (Language('KOREAN'), Language('FRENCH')),
            (Language('KOREAN'), Language('GERMAN')),
            (Language('KOREAN'), Language('GREEK')),
            (Language('KOREAN'), Language('HEBREW')),
            (Language('KOREAN'), Language('HINDI')),
            (Language('KOREAN'), Language('INDONESIAN')),
            (Language('KOREAN'), Language('ITALIAN')),
            (Language('KOREAN'), Language('JAPANESE')),
            (Language('KOREAN'), Language('KOREAN')),
            (Language('KOREAN'), Language('LATVIAN')),
            (Language('KOREAN'), Language('LITHUANIAN')),
            (Language('KOREAN'), Language('NORWEGIAN')),
            (Language('KOREAN'), Language('POLISH')),
            (Language('KOREAN'), Language('PORTUGUESE')),
            (Language('KOREAN'), Language('ROMANIAN')),
            (Language('KOREAN'), Language('RUSSIAN')),
            (Language('KOREAN'), Language('SPANISH')),
            (Language('KOREAN'), Language('SERBIAN')),
            (Language('KOREAN'), Language('SLOVAK')),
            (Language('KOREAN'), Language('SLOVENIAN')),
            (Language('KOREAN'), Language('SWEDISH')),
            (Language('KOREAN'), Language('UKRAINIAN')),
            (Language('KOREAN'), Language('VIETNAMESE')),

            # LATVIAN PAIR
            (Language('LATVIAN'), Language('ARABIC')),
            (Language('LATVIAN'), Language('BULGARIAN')),
            (Language('LATVIAN'), Language('CHINESE')),
            (Language('LATVIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('LATVIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('LATVIAN'), Language('CATALAN')),
            (Language('LATVIAN'), Language('CROATIAN')),
            (Language('LATVIAN'), Language('CZECH')),
            (Language('LATVIAN'), Language('DANISH')),
            (Language('LATVIAN'), Language('DUTCH')),
            (Language('LATVIAN'), Language('ENGLISH')),
            (Language('LATVIAN'), Language('FILIPINO')),
            (Language('LATVIAN'), Language('FINNISH')),
            (Language('LATVIAN'), Language('FRENCH')),
            (Language('LATVIAN'), Language('GERMAN')),
            (Language('LATVIAN'), Language('GREEK')),
            (Language('LATVIAN'), Language('HEBREW')),
            (Language('LATVIAN'), Language('HINDI')),
            (Language('LATVIAN'), Language('INDONESIAN')),
            (Language('LATVIAN'), Language('ITALIAN')),
            (Language('LATVIAN'), Language('JAPANESE')),
            (Language('LATVIAN'), Language('KOREAN')),
            (Language('LATVIAN'), Language('LATVIAN')),
            (Language('LATVIAN'), Language('LITHUANIAN')),
            (Language('LATVIAN'), Language('NORWEGIAN')),
            (Language('LATVIAN'), Language('POLISH')),
            (Language('LATVIAN'), Language('PORTUGUESE')),
            (Language('LATVIAN'), Language('ROMANIAN')),
            (Language('LATVIAN'), Language('RUSSIAN')),
            (Language('LATVIAN'), Language('SPANISH')),
            (Language('LATVIAN'), Language('SERBIAN')),
            (Language('LATVIAN'), Language('SLOVAK')),
            (Language('LATVIAN'), Language('SLOVENIAN')),
            (Language('LATVIAN'), Language('SWEDISH')),
            (Language('LATVIAN'), Language('UKRAINIAN')),
            (Language('LATVIAN'), Language('VIETNAMESE')),

            # LITHUANIAN
            (Language('LITHUANIAN'), Language('ARABIC')),
            (Language('LITHUANIAN'), Language('BULGARIAN')),
            (Language('LITHUANIAN'), Language('CHINESE')),
            (Language('LITHUANIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('LITHUANIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('LITHUANIAN'), Language('CATALAN')),
            (Language('LITHUANIAN'), Language('CROATIAN')),
            (Language('LITHUANIAN'), Language('CZECH')),
            (Language('LITHUANIAN'), Language('DANISH')),
            (Language('LITHUANIAN'), Language('DUTCH')),
            (Language('LITHUANIAN'), Language('ENGLISH')),
            (Language('LITHUANIAN'), Language('FILIPINO')),
            (Language('LITHUANIAN'), Language('FINNISH')),
            (Language('LITHUANIAN'), Language('FRENCH')),
            (Language('LITHUANIAN'), Language('GERMAN')),
            (Language('LITHUANIAN'), Language('GREEK')),
            (Language('LITHUANIAN'), Language('HEBREW')),
            (Language('LITHUANIAN'), Language('HINDI')),
            (Language('LITHUANIAN'), Language('INDONESIAN')),
            (Language('LITHUANIAN'), Language('ITALIAN')),
            (Language('LITHUANIAN'), Language('JAPANESE')),
            (Language('LITHUANIAN'), Language('KOREAN')),
            (Language('LITHUANIAN'), Language('LATVIAN')),
            (Language('LITHUANIAN'), Language('LITHUANIAN')),
            (Language('LITHUANIAN'), Language('NORWEGIAN')),
            (Language('LITHUANIAN'), Language('POLISH')),
            (Language('LITHUANIAN'), Language('PORTUGUESE')),
            (Language('LITHUANIAN'), Language('ROMANIAN')),
            (Language('LITHUANIAN'), Language('RUSSIAN')),
            (Language('LITHUANIAN'), Language('SPANISH')),
            (Language('LITHUANIAN'), Language('SERBIAN')),
            (Language('LITHUANIAN'), Language('SLOVAK')),
            (Language('LITHUANIAN'), Language('SLOVENIAN')),
            (Language('LITHUANIAN'), Language('SWEDISH')),
            (Language('LITHUANIAN'), Language('UKRAINIAN')),
            (Language('LITHUANIAN'), Language('VIETNAMESE')),

            # NORWEGIAN PAIR
            (Language('NORWEGIAN'), Language('ARABIC')),
            (Language('NORWEGIAN'), Language('BULGARIAN')),
            (Language('NORWEGIAN'), Language('CHINESE')),
            (Language('NORWEGIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('NORWEGIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('NORWEGIAN'), Language('CATALAN')),
            (Language('NORWEGIAN'), Language('CROATIAN')),
            (Language('NORWEGIAN'), Language('CZECH')),
            (Language('NORWEGIAN'), Language('DANISH')),
            (Language('NORWEGIAN'), Language('DUTCH')),
            (Language('NORWEGIAN'), Language('ENGLISH')),
            (Language('NORWEGIAN'), Language('FILIPINO')),
            (Language('NORWEGIAN'), Language('FINNISH')),
            (Language('NORWEGIAN'), Language('FRENCH')),
            (Language('NORWEGIAN'), Language('GERMAN')),
            (Language('NORWEGIAN'), Language('GREEK')),
            (Language('NORWEGIAN'), Language('HEBREW')),
            (Language('NORWEGIAN'), Language('HINDI')),
            (Language('NORWEGIAN'), Language('INDONESIAN')),
            (Language('NORWEGIAN'), Language('ITALIAN')),
            (Language('NORWEGIAN'), Language('JAPANESE')),
            (Language('NORWEGIAN'), Language('KOREAN')),
            (Language('NORWEGIAN'), Language('LATVIAN')),
            (Language('NORWEGIAN'), Language('LITHUANIAN')),
            (Language('NORWEGIAN'), Language('NORWEGIAN')),
            (Language('NORWEGIAN'), Language('POLISH')),
            (Language('NORWEGIAN'), Language('PORTUGUESE')),
            (Language('NORWEGIAN'), Language('ROMANIAN')),
            (Language('NORWEGIAN'), Language('RUSSIAN')),
            (Language('NORWEGIAN'), Language('SPANISH')),
            (Language('NORWEGIAN'), Language('SERBIAN')),
            (Language('NORWEGIAN'), Language('SLOVAK')),
            (Language('NORWEGIAN'), Language('SLOVENIAN')),
            (Language('NORWEGIAN'), Language('SWEDISH')),
            (Language('NORWEGIAN'), Language('UKRAINIAN')),
            (Language('NORWEGIAN'), Language('VIETNAMESE')),

            # POLISH PAIR
            (Language('POLISH'), Language('ARABIC')),
            (Language('POLISH'), Language('BULGARIAN')),
            (Language('POLISH'), Language('CHINESE')),
            (Language('POLISH'), Language('CHINESE_TRADITIONAL')),
            (Language('POLISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('POLISH'), Language('CATALAN')),
            (Language('POLISH'), Language('CROATIAN')),
            (Language('POLISH'), Language('CZECH')),
            (Language('POLISH'), Language('DANISH')),
            (Language('POLISH'), Language('DUTCH')),
            (Language('POLISH'), Language('ENGLISH')),
            (Language('POLISH'), Language('FILIPINO')),
            (Language('POLISH'), Language('FINNISH')),
            (Language('POLISH'), Language('FRENCH')),
            (Language('POLISH'), Language('GERMAN')),
            (Language('POLISH'), Language('GREEK')),
            (Language('POLISH'), Language('HEBREW')),
            (Language('POLISH'), Language('HINDI')),
            (Language('POLISH'), Language('INDONESIAN')),
            (Language('POLISH'), Language('ITALIAN')),
            (Language('POLISH'), Language('JAPANESE')),
            (Language('POLISH'), Language('KOREAN')),
            (Language('POLISH'), Language('LATVIAN')),
            (Language('POLISH'), Language('LITHUANIAN')),
            (Language('POLISH'), Language('NORWEGIAN')),
            (Language('POLISH'), Language('POLISH')),
            (Language('POLISH'), Language('PORTUGUESE')),
            (Language('POLISH'), Language('ROMANIAN')),
            (Language('POLISH'), Language('RUSSIAN')),
            (Language('POLISH'), Language('SPANISH')),
            (Language('POLISH'), Language('SERBIAN')),
            (Language('POLISH'), Language('SLOVAK')),
            (Language('POLISH'), Language('SLOVENIAN')),
            (Language('POLISH'), Language('SWEDISH')),
            (Language('POLISH'), Language('UKRAINIAN')),
            (Language('POLISH'), Language('VIETNAMESE')),

            # PORTUGUESE PAIR
            (Language('PORTUGUESE'), Language('ARABIC')),
            (Language('PORTUGUESE'), Language('BULGARIAN')),
            (Language('PORTUGUESE'), Language('CHINESE')),
            (Language('PORTUGUESE'), Language('CHINESE_TRADITIONAL')),
            (Language('PORTUGUESE'), Language('CHINESE_SIMPLIFIED')),
            (Language('PORTUGUESE'), Language('CATALAN')),
            (Language('PORTUGUESE'), Language('CROATIAN')),
            (Language('PORTUGUESE'), Language('CZECH')),
            (Language('PORTUGUESE'), Language('DANISH')),
            (Language('PORTUGUESE'), Language('DUTCH')),
            (Language('PORTUGUESE'), Language('ENGLISH')),
            (Language('PORTUGUESE'), Language('FILIPINO')),
            (Language('PORTUGUESE'), Language('FINNISH')),
            (Language('PORTUGUESE'), Language('FRENCH')),
            (Language('PORTUGUESE'), Language('GERMAN')),
            (Language('PORTUGUESE'), Language('GREEK')),
            (Language('PORTUGUESE'), Language('HEBREW')),
            (Language('PORTUGUESE'), Language('HINDI')),
            (Language('PORTUGUESE'), Language('INDONESIAN')),
            (Language('PORTUGUESE'), Language('ITALIAN')),
            (Language('PORTUGUESE'), Language('JAPANESE')),
            (Language('PORTUGUESE'), Language('KOREAN')),
            (Language('PORTUGUESE'), Language('LATVIAN')),
            (Language('PORTUGUESE'), Language('LITHUANIAN')),
            (Language('PORTUGUESE'), Language('NORWEGIAN')),
            (Language('PORTUGUESE'), Language('POLISH')),
            (Language('PORTUGUESE'), Language('PORTUGUESE')),
            (Language('PORTUGUESE'), Language('ROMANIAN')),
            (Language('PORTUGUESE'), Language('RUSSIAN')),
            (Language('PORTUGUESE'), Language('SPANISH')),
            (Language('PORTUGUESE'), Language('SERBIAN')),
            (Language('PORTUGUESE'), Language('SLOVAK')),
            (Language('PORTUGUESE'), Language('SLOVENIAN')),
            (Language('PORTUGUESE'), Language('SWEDISH')),
            (Language('PORTUGUESE'), Language('UKRAINIAN')),
            (Language('PORTUGUESE'), Language('VIETNAMESE')),

            # ROMANIAN PAIR
            (Language('ROMANIAN'), Language('ARABIC')),
            (Language('ROMANIAN'), Language('BULGARIAN')),
            (Language('ROMANIAN'), Language('CHINESE')),
            (Language('ROMANIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('ROMANIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('ROMANIAN'), Language('CATALAN')),
            (Language('ROMANIAN'), Language('CROATIAN')),
            (Language('ROMANIAN'), Language('CZECH')),
            (Language('ROMANIAN'), Language('DANISH')),
            (Language('ROMANIAN'), Language('DUTCH')),
            (Language('ROMANIAN'), Language('ENGLISH')),
            (Language('ROMANIAN'), Language('FILIPINO')),
            (Language('ROMANIAN'), Language('FINNISH')),
            (Language('ROMANIAN'), Language('FRENCH')),
            (Language('ROMANIAN'), Language('GERMAN')),
            (Language('ROMANIAN'), Language('GREEK')),
            (Language('ROMANIAN'), Language('HEBREW')),
            (Language('ROMANIAN'), Language('HINDI')),
            (Language('ROMANIAN'), Language('INDONESIAN')),
            (Language('ROMANIAN'), Language('ITALIAN')),
            (Language('ROMANIAN'), Language('JAPANESE')),
            (Language('ROMANIAN'), Language('KOREAN')),
            (Language('ROMANIAN'), Language('LATVIAN')),
            (Language('ROMANIAN'), Language('LITHUANIAN')),
            (Language('ROMANIAN'), Language('NORWEGIAN')),
            (Language('ROMANIAN'), Language('POLISH')),
            (Language('ROMANIAN'), Language('PORTUGUESE')),
            (Language('ROMANIAN'), Language('ROMANIAN')),
            (Language('ROMANIAN'), Language('RUSSIAN')),
            (Language('ROMANIAN'), Language('SPANISH')),
            (Language('ROMANIAN'), Language('SERBIAN')),
            (Language('ROMANIAN'), Language('SLOVAK')),
            (Language('ROMANIAN'), Language('SLOVENIAN')),
            (Language('ROMANIAN'), Language('SWEDISH')),
            (Language('ROMANIAN'), Language('UKRAINIAN')),
            (Language('ROMANIAN'), Language('VIETNAMESE')),

            # RUSSIAN PAIR
            (Language('RUSSIAN'), Language('ARABIC')),
            (Language('RUSSIAN'), Language('BULGARIAN')),
            (Language('RUSSIAN'), Language('CHINESE')),
            (Language('RUSSIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('RUSSIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('RUSSIAN'), Language('CATALAN')),
            (Language('RUSSIAN'), Language('CROATIAN')),
            (Language('RUSSIAN'), Language('CZECH')),
            (Language('RUSSIAN'), Language('DANISH')),
            (Language('RUSSIAN'), Language('DUTCH')),
            (Language('RUSSIAN'), Language('ENGLISH')),
            (Language('RUSSIAN'), Language('FILIPINO')),
            (Language('RUSSIAN'), Language('FINNISH')),
            (Language('RUSSIAN'), Language('FRENCH')),
            (Language('RUSSIAN'), Language('GERMAN')),
            (Language('RUSSIAN'), Language('GREEK')),
            (Language('RUSSIAN'), Language('HEBREW')),
            (Language('RUSSIAN'), Language('HINDI')),
            (Language('RUSSIAN'), Language('INDONESIAN')),
            (Language('RUSSIAN'), Language('ITALIAN')),
            (Language('RUSSIAN'), Language('JAPANESE')),
            (Language('RUSSIAN'), Language('KOREAN')),
            (Language('RUSSIAN'), Language('LATVIAN')),
            (Language('RUSSIAN'), Language('LITHUANIAN')),
            (Language('RUSSIAN'), Language('NORWEGIAN')),
            (Language('RUSSIAN'), Language('POLISH')),
            (Language('RUSSIAN'), Language('PORTUGUESE')),
            (Language('RUSSIAN'), Language('ROMANIAN')),
            (Language('RUSSIAN'), Language('RUSSIAN')),
            (Language('RUSSIAN'), Language('SPANISH')),
            (Language('RUSSIAN'), Language('SERBIAN')),
            (Language('RUSSIAN'), Language('SLOVAK')),
            (Language('RUSSIAN'), Language('SLOVENIAN')),
            (Language('RUSSIAN'), Language('SWEDISH')),
            (Language('RUSSIAN'), Language('UKRAINIAN')),
            (Language('RUSSIAN'), Language('VIETNAMESE')),

            # SPANISH PAIR
                    (Language('SPANISH'), Language('ARABIC')),
            (Language('SPANISH'), Language('BULGARIAN')),
            (Language('SPANISH'), Language('CHINESE')),
            (Language('SPANISH'), Language('CHINESE_TRADITIONAL')),
            (Language('SPANISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('SPANISH'), Language('CATALAN')),
            (Language('SPANISH'), Language('CROATIAN')),
            (Language('SPANISH'), Language('CZECH')),
            (Language('SPANISH'), Language('DANISH')),
            (Language('SPANISH'), Language('DUTCH')),
            (Language('SPANISH'), Language('ENGLISH')),
            (Language('SPANISH'), Language('FILIPINO')),
            (Language('SPANISH'), Language('FINNISH')),
            (Language('SPANISH'), Language('FRENCH')),
            (Language('SPANISH'), Language('GERMAN')),
            (Language('SPANISH'), Language('GREEK')),
            (Language('SPANISH'), Language('HEBREW')),
            (Language('SPANISH'), Language('HINDI')),
            (Language('SPANISH'), Language('INDONESIAN')),
            (Language('SPANISH'), Language('ITALIAN')),
            (Language('SPANISH'), Language('JAPANESE')),
            (Language('SPANISH'), Language('KOREAN')),
            (Language('SPANISH'), Language('LATVIAN')),
            (Language('SPANISH'), Language('LITHUANIAN')),
            (Language('SPANISH'), Language('NORWEGIAN')),
            (Language('SPANISH'), Language('POLISH')),
            (Language('SPANISH'), Language('PORTUGUESE')),
            (Language('SPANISH'), Language('ROMANIAN')),
            (Language('SPANISH'), Language('RUSSIAN')),
            (Language('SPANISH'), Language('SPANISH')),
            (Language('SPANISH'), Language('SERBIAN')),
            (Language('SPANISH'), Language('SLOVAK')),
            (Language('SPANISH'), Language('SLOVENIAN')),
            (Language('SPANISH'), Language('SWEDISH')),
            (Language('SPANISH'), Language('UKRAINIAN')),
            (Language('SPANISH'), Language('VIETNAMESE')),

            # SERBIAN PAIR
            (Language('SERBIAN'), Language('ARABIC')),
            (Language('SERBIAN'), Language('BULGARIAN')),
            (Language('SERBIAN'), Language('CHINESE')),
            (Language('SERBIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('SERBIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('SERBIAN'), Language('CATALAN')),
            (Language('SERBIAN'), Language('CROATIAN')),
            (Language('SERBIAN'), Language('CZECH')),
            (Language('SERBIAN'), Language('DANISH')),
            (Language('SERBIAN'), Language('DUTCH')),
            (Language('SERBIAN'), Language('ENGLISH')),
            (Language('SERBIAN'), Language('FILIPINO')),
            (Language('SERBIAN'), Language('FINNISH')),
            (Language('SERBIAN'), Language('FRENCH')),
            (Language('SERBIAN'), Language('GERMAN')),
            (Language('SERBIAN'), Language('GREEK')),
            (Language('SERBIAN'), Language('HEBREW')),
            (Language('SERBIAN'), Language('HINDI')),
            (Language('SERBIAN'), Language('INDONESIAN')),
            (Language('SERBIAN'), Language('ITALIAN')),
            (Language('SERBIAN'), Language('JAPANESE')),
            (Language('SERBIAN'), Language('KOREAN')),
            (Language('SERBIAN'), Language('LATVIAN')),
            (Language('SERBIAN'), Language('LITHUANIAN')),
            (Language('SERBIAN'), Language('NORWEGIAN')),
            (Language('SERBIAN'), Language('POLISH')),
            (Language('SERBIAN'), Language('PORTUGUESE')),
            (Language('SERBIAN'), Language('ROMANIAN')),
            (Language('SERBIAN'), Language('RUSSIAN')),
            (Language('SERBIAN'), Language('SPANISH')),
            (Language('SERBIAN'), Language('SERBIAN')),
            (Language('SERBIAN'), Language('SLOVAK')),
            (Language('SERBIAN'), Language('SLOVENIAN')),
            (Language('SERBIAN'), Language('SWEDISH')),
            (Language('SERBIAN'), Language('UKRAINIAN')),
            (Language('SERBIAN'), Language('VIETNAMESE')),

            # SLOVAK PAIR
            (Language('SLOVAK'), Language('ARABIC')),
            (Language('SLOVAK'), Language('BULGARIAN')),
            (Language('SLOVAK'), Language('CHINESE')),
            (Language('SLOVAK'), Language('CHINESE_TRADITIONAL')),
            (Language('SLOVAK'), Language('CHINESE_SIMPLIFIED')),
            (Language('SLOVAK'), Language('CATALAN')),
            (Language('SLOVAK'), Language('CROATIAN')),
            (Language('SLOVAK'), Language('CZECH')),
            (Language('SLOVAK'), Language('DANISH')),
            (Language('SLOVAK'), Language('DUTCH')),
            (Language('SLOVAK'), Language('ENGLISH')),
            (Language('SLOVAK'), Language('FILIPINO')),
            (Language('SLOVAK'), Language('FINNISH')),
            (Language('SLOVAK'), Language('FRENCH')),
            (Language('SLOVAK'), Language('GERMAN')),
            (Language('SLOVAK'), Language('GREEK')),
            (Language('SLOVAK'), Language('HEBREW')),
            (Language('SLOVAK'), Language('HINDI')),
            (Language('SLOVAK'), Language('INDONESIAN')),
            (Language('SLOVAK'), Language('ITALIAN')),
            (Language('SLOVAK'), Language('JAPANESE')),
            (Language('SLOVAK'), Language('KOREAN')),
            (Language('SLOVAK'), Language('LATVIAN')),
            (Language('SLOVAK'), Language('LITHUANIAN')),
            (Language('SLOVAK'), Language('NORWEGIAN')),
            (Language('SLOVAK'), Language('POLISH')),
            (Language('SLOVAK'), Language('PORTUGUESE')),
            (Language('SLOVAK'), Language('ROMANIAN')),
            (Language('SLOVAK'), Language('RUSSIAN')),
            (Language('SLOVAK'), Language('SPANISH')),
            (Language('SLOVAK'), Language('SERBIAN')),
            (Language('SLOVAK'), Language('SLOVAK')),
            (Language('SLOVAK'), Language('SLOVENIAN')),
            (Language('SLOVAK'), Language('SWEDISH')),
            (Language('SLOVAK'), Language('UKRAINIAN')),
            (Language('SLOVAK'), Language('VIETNAMESE')),

            # SLOVENIAN PAIR
            (Language('SLOVENIAN'), Language('ARABIC')),
            (Language('SLOVENIAN'), Language('BULGARIAN')),
            (Language('SLOVENIAN'), Language('CHINESE')),
            (Language('SLOVENIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('SLOVENIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('SLOVENIAN'), Language('CATALAN')),
            (Language('SLOVENIAN'), Language('CROATIAN')),
            (Language('SLOVENIAN'), Language('CZECH')),
            (Language('SLOVENIAN'), Language('DANISH')),
            (Language('SLOVENIAN'), Language('DUTCH')),
            (Language('SLOVENIAN'), Language('ENGLISH')),
            (Language('SLOVENIAN'), Language('FILIPINO')),
            (Language('SLOVENIAN'), Language('FINNISH')),
            (Language('SLOVENIAN'), Language('FRENCH')),
            (Language('SLOVENIAN'), Language('GERMAN')),
            (Language('SLOVENIAN'), Language('GREEK')),
            (Language('SLOVENIAN'), Language('HEBREW')),
            (Language('SLOVENIAN'), Language('HINDI')),
            (Language('SLOVENIAN'), Language('INDONESIAN')),
            (Language('SLOVENIAN'), Language('ITALIAN')),
            (Language('SLOVENIAN'), Language('JAPANESE')),
            (Language('SLOVENIAN'), Language('KOREAN')),
            (Language('SLOVENIAN'), Language('LATVIAN')),
            (Language('SLOVENIAN'), Language('LITHUANIAN')),
            (Language('SLOVENIAN'), Language('NORWEGIAN')),
            (Language('SLOVENIAN'), Language('POLISH')),
            (Language('SLOVENIAN'), Language('PORTUGUESE')),
            (Language('SLOVENIAN'), Language('ROMANIAN')),
            (Language('SLOVENIAN'), Language('RUSSIAN')),
            (Language('SLOVENIAN'), Language('SPANISH')),
            (Language('SLOVENIAN'), Language('SERBIAN')),
            (Language('SLOVENIAN'), Language('SLOVAK')),
            (Language('SLOVENIAN'), Language('SLOVENIAN')),
            (Language('SLOVENIAN'), Language('SWEDISH')),
            (Language('SLOVENIAN'), Language('UKRAINIAN')),
            (Language('SLOVENIAN'), Language('VIETNAMESE')),

            # SWEDISH PAIR
            (Language('SWEDISH'), Language('ARABIC')),
            (Language('SWEDISH'), Language('BULGARIAN')),
            (Language('SWEDISH'), Language('CHINESE')),
            (Language('SWEDISH'), Language('CHINESE_TRADITIONAL')),
            (Language('SWEDISH'), Language('CHINESE_SIMPLIFIED')),
            (Language('SWEDISH'), Language('CATALAN')),
            (Language('SWEDISH'), Language('CROATIAN')),
            (Language('SWEDISH'), Language('CZECH')),
            (Language('SWEDISH'), Language('DANISH')),
            (Language('SWEDISH'), Language('DUTCH')),
            (Language('SWEDISH'), Language('ENGLISH')),
            (Language('SWEDISH'), Language('FILIPINO')),
            (Language('SWEDISH'), Language('FINNISH')),
            (Language('SWEDISH'), Language('FRENCH')),
            (Language('SWEDISH'), Language('GERMAN')),
            (Language('SWEDISH'), Language('GREEK')),
            (Language('SWEDISH'), Language('HEBREW')),
            (Language('SWEDISH'), Language('HINDI')),
            (Language('SWEDISH'), Language('INDONESIAN')),
            (Language('SWEDISH'), Language('ITALIAN')),
            (Language('SWEDISH'), Language('JAPANESE')),
            (Language('SWEDISH'), Language('KOREAN')),
            (Language('SWEDISH'), Language('LATVIAN')),
            (Language('SWEDISH'), Language('LITHUANIAN')),
            (Language('SWEDISH'), Language('NORWEGIAN')),
            (Language('SWEDISH'), Language('POLISH')),
            (Language('SWEDISH'), Language('PORTUGUESE')),
            (Language('SWEDISH'), Language('ROMANIAN')),
            (Language('SWEDISH'), Language('RUSSIAN')),
            (Language('SWEDISH'), Language('SPANISH')),
            (Language('SWEDISH'), Language('SERBIAN')),
            (Language('SWEDISH'), Language('SLOVAK')),
            (Language('SWEDISH'), Language('SLOVENIAN')),
            (Language('SWEDISH'), Language('SWEDISH')),
            (Language('SWEDISH'), Language('UKRAINIAN')),
            (Language('SWEDISH'), Language('VIETNAMESE')),

            # UKRAINIAN PAIR
            (Language('UKRAINIAN'), Language('ARABIC')),
            (Language('UKRAINIAN'), Language('BULGARIAN')),
            (Language('UKRAINIAN'), Language('CHINESE')),
            (Language('UKRAINIAN'), Language('CHINESE_TRADITIONAL')),
            (Language('UKRAINIAN'), Language('CHINESE_SIMPLIFIED')),
            (Language('UKRAINIAN'), Language('CATALAN')),
            (Language('UKRAINIAN'), Language('CROATIAN')),
            (Language('UKRAINIAN'), Language('CZECH')),
            (Language('UKRAINIAN'), Language('DANISH')),
            (Language('UKRAINIAN'), Language('DUTCH')),
            (Language('UKRAINIAN'), Language('ENGLISH')),
            (Language('UKRAINIAN'), Language('FILIPINO')),
            (Language('UKRAINIAN'), Language('FINNISH')),
            (Language('UKRAINIAN'), Language('FRENCH')),
            (Language('UKRAINIAN'), Language('GERMAN')),
            (Language('UKRAINIAN'), Language('GREEK')),
            (Language('UKRAINIAN'), Language('HEBREW')),
            (Language('UKRAINIAN'), Language('HINDI')),
            (Language('UKRAINIAN'), Language('INDONESIAN')),
            (Language('UKRAINIAN'), Language('ITALIAN')),
            (Language('UKRAINIAN'), Language('JAPANESE')),
            (Language('UKRAINIAN'), Language('KOREAN')),
            (Language('UKRAINIAN'), Language('LATVIAN')),
            (Language('UKRAINIAN'), Language('LITHUANIAN')),
            (Language('UKRAINIAN'), Language('NORWEGIAN')),
            (Language('UKRAINIAN'), Language('POLISH')),
            (Language('UKRAINIAN'), Language('PORTUGUESE')),
            (Language('UKRAINIAN'), Language('ROMANIAN')),
            (Language('UKRAINIAN'), Language('RUSSIAN')),
            (Language('UKRAINIAN'), Language('SPANISH')),
            (Language('UKRAINIAN'), Language('SERBIAN')),
            (Language('UKRAINIAN'), Language('SLOVAK')),
            (Language('UKRAINIAN'), Language('SLOVENIAN')),
            (Language('UKRAINIAN'), Language('SWEDISH')),
            (Language('UKRAINIAN'), Language('UKRAINIAN')),
            (Language('UKRAINIAN'), Language('VIETNAMESE')),

            # VIETNAMESE PAIR
            (Language('VIETNAMESE'), Language('ARABIC')),
            (Language('VIETNAMESE'), Language('BULGARIAN')),
            (Language('VIETNAMESE'), Language('CHINESE')),
            (Language('VIETNAMESE'), Language('CHINESE_TRADITIONAL')),
            (Language('VIETNAMESE'), Language('CHINESE_SIMPLIFIED')),
            (Language('VIETNAMESE'), Language('CATALAN')),
            (Language('VIETNAMESE'), Language('CROATIAN')),
            (Language('VIETNAMESE'), Language('CZECH')),
            (Language('VIETNAMESE'), Language('DANISH')),
            (Language('VIETNAMESE'), Language('DUTCH')),
            (Language('VIETNAMESE'), Language('ENGLISH')),
            (Language('VIETNAMESE'), Language('FILIPINO')),
            (Language('VIETNAMESE'), Language('FINNISH')),
            (Language('VIETNAMESE'), Language('FRENCH')),
            (Language('VIETNAMESE'), Language('GERMAN')),
            (Language('VIETNAMESE'), Language('GREEK')),
            (Language('VIETNAMESE'), Language('HEBREW')),
            (Language('VIETNAMESE'), Language('HINDI')),
            (Language('VIETNAMESE'), Language('INDONESIAN')),
            (Language('VIETNAMESE'), Language('ITALIAN')),
            (Language('VIETNAMESE'), Language('JAPANESE')),
            (Language('VIETNAMESE'), Language('KOREAN')),
            (Language('VIETNAMESE'), Language('LATVIAN')),
            (Language('VIETNAMESE'), Language('LITHUANIAN')),
            (Language('VIETNAMESE'), Language('NORWEGIAN')),
            (Language('VIETNAMESE'), Language('POLISH')),
            (Language('VIETNAMESE'), Language('PORTUGUESE')),
            (Language('VIETNAMESE'), Language('ROMANIAN')),
            (Language('VIETNAMESE'), Language('RUSSIAN')),
            (Language('VIETNAMESE'), Language('SPANISH')),
            (Language('VIETNAMESE'), Language('SERBIAN')),
            (Language('VIETNAMESE'), Language('SLOVAK')),
            (Language('VIETNAMESE'), Language('SLOVENIAN')),
            (Language('VIETNAMESE'), Language('SWEDISH')),
            (Language('VIETNAMESE'), Language('UKRAINIAN')),
            (Language('VIETNAMESE'), Language('VIETNAMESE')),


    )

    @staticmethod
    def is_valid_language_pair(language_origin, language_destiny):
        """ Checks if a language pair to be translated is valid """
        return (language_origin, language_destiny) \
               in Translation.translation_pairs

    def __init__(self, language_origin, language_destiny):
        """
        Creates a language pair where it is
        possible to translate languageA to languageB

        language_origin -- The origin language (Language)
        language_destiny -- The destination language (Language)
        """
        if not Translation.is_valid_language_pair(language_origin,
                                                  language_destiny):
            raise Exception, ("The translation %s to %s is not valid. Don't even bother trying again :)"
                              % (language_origin, language_destiny))

        self.language_origin = language_origin
        self.language_destiny = language_destiny

    def __str__(self):
        """
        """
        return  u'%s|%s' % (self.language_origin, self.language_destiny)


